apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: microservice-user-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: microservice-user
    kind: Deployment
  minReplicas: 1
  maxReplicas: 15
  targetCPUUtilizationPercentage: 25