apiVersion: v1
kind: Service
metadata:
  name: microservice-tweet-service
spec:
  selector:
    app: microservice-tweet
  type: ClusterIP
  ports:
  - name: microservice-tweet-service
    port: 80
    targetPort: 8001
    protocol: TCP
    