apiVersion: v1
kind: Service
metadata:
  name: microservice-user-service
spec:
  selector:
    app: microservice-user
  type: ClusterIP
  ports:
  - name: microservice-user-service
    port: 80
    targetPort: 8000
    protocol: TCP
    